name = "dive25-status"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "5e6eab7fd1f83293e26dd6c9407f187c"

# Custom domain for the status API
# routes = [
#   { pattern = "status-api.dive25.com", custom_domain = true }
# ]

